### ISSUE TITLE
inflectors.singularize('indices') -> 'indice'

### ISSUE THREAD

**Issue by gr2m** [billysbilling/inflectors#2]
```js
var inflectors = require('inflectors');
inflectors.singularize('indices')
// returns "indice", but should be "index"
```

**Comment by gr2m** [comment]
I wonder, do you still maintain this package? Are you aware if there are alternatives for pluralization / signalization in npm land?

**Comment by mex** [comment]
There are a bunch of inflection libraries on npm, but you could solve this particular case by adding a rule like this:
```
var inflectors = require('inflectors');
inflectors.addRule('indices', 'index');
inflectors.singularize('indices')
// returns "index"
```
_Note: Untested_

**Comment by gr2m** [comment]
yeah, that's how I solved it now, cheers.
